#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

echo "Running check_jenkinsfiles.sh..."
ls tools/githooks_scripts
tools/githooks_scripts/check_jenkinsfiles.sh
JENKINSFILE_CHECK_EXIT_CODE=$?

if [ $JENKINSFILE_CHECK_EXIT_CODE -ne 0 ]; then
    echo "Jenkinsfile check failed."
    exit 1
else
    echo "Jenkinsfile check succeeded."
fi

git add -f "$STAGED_FILES"

exit 0